services:
  commentmap-mvc:
    image: ghcr.io/adedw/commentmap-mvc:master
    build:
      context: ./CommentMap.Mvc
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=comment-map;Username=comment-map;Password=P@ssw0rd"
      AllowedHosts: "*"
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Release
      Serilog__MinimumLevel__Default: Information
      Serilog__MinimumLevel__Override__Microsoft.AspNetCore: Warning
      Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore: Warning
      Serilog__WriteTo__0__Name: Console
    container_name: commentmap-mvc
    ports:
      - "127.0.0.1:8080:8080" 
      
  postgres:
    container_name: postgres
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: comment-map
      POSTGRES_USER: comment-map
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "127.0.0.1:5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"
      
  commentmap-emailsender:
    image: ${DOCKER_REGISTRY-}commentmap-emailsender
    build:
      context: .
      dockerfile: CommentMap.EmailSender/Dockerfile
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0.4-management
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: commentmap
      RABBITMQ_DEFAULT_PASS: P@ssw0rd
      RABBITMQ_DEFAULT_VHOST: commentmap
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia

volumes:
  pg-data:
  rabbitmq-data:
