services:
  postgres:
    container_name: postgres
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: comment-map
      POSTGRES_USER: comment-map
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "127.0.0.1:5432:5432"

  commentmap-mvc:
    image: ghcr.io/adedw/commentmap:master
    build:
      context: ./CommentMap.Mvc
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=comment-map;Username=comment-map;Password=P@ssw0rd"
      AllowedHosts: "*"
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Release
      Serilog__MinimumLevel__Default: Information
      Serilog__MinimumLevel__Override__Microsoft.AspNetCore: Warning
      Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore: Warning
      Serilog__WriteTo__0__Name: Console
    container_name: commentmap-mvc
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  pg-data:
