<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CommentMap.EmailSender-79f62d41-e375-4e59-9348-362f9f72db30</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Mjml.Net" />
    <PackageReference Include="RazorBlade" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommentMap.EventBus\CommentMap.EventBus.csproj" />
    <ProjectReference Include="..\CommentMap.ServiceDefaults\CommentMap.ServiceDefaults.csproj" />
    <ProjectReference Include="..\CommentMap.Shared\CommentMap.Shared.csproj" />
  </ItemGroup>
</Project>
